version: "3.9"

services:
  mariadb:
    image: mariadb:10.11
    container_name: tp2-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supervision
    ports:
      - "3307:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - tp-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: tp2-backend
    restart: always
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: supervision
      DB_PORT: 3306
      PORT: 3000
      PLC_IP: 172.16.1.24
      PLC_PORT: 502
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - tp-net

  frontend:
    build: ./frontend
    container_name: tp2-frontend
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      - tp-net

volumes:
  mariadb_data:

networks:
  tp-net:
    driver: bridge
